dashboard/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *
app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='home'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.Logout, name='logout'),
    path('profile/update/', views.profile_update, name="update-profile"),
    path('profile', login_required(ProfileView.as_view(),
                                   login_url='  /user/login'), name='profile-portal-home'),
    url('^$', login_required(FinancingPortalHomeView.as_view(),
        login_url='/user/login'), name='financing-portal-home'),

    path('purchase_products', login_required(FinancingPortalPurchaseProductsView.as_view(
    ), login_url='/user/login'), name='purchase-products'),
    path('payments', login_required(FinancingPortalPaymentsView.as_view(),
                                    login_url='/user/login'), name='payments'),
    path('products_purchased', login_required(FinancingPortalProductsPurchasedView.as_view(
    ), login_url='/user/login'), name='products-purchased'),
    path('access_software', login_required(FinancingPortalAccessSoftware.as_view(
    ), login_url='/user/login'), name='products-access'),
    path('confirm_purchase/<int:pk>', login_required(
        FinancingPortalConfirmPurchaseView.as_view()), name="confirm-purchase"),
    path('plans/', login_required(views.plans,
         login_url='/user/login'), name='plans'),
    path('apply_for_loan/<str:step>', apply_for_loan, name='apply_for_loan'),

   

]

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
import debug_toolbar
from django.urls import include, path
from django.conf.urls.static import static
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('case_studies/', views.case_studies, name='case_studies'),
    path('contact/', views.contact, name='contact'),
    path('send_email/', views.send_email, name='send_mail'),
    path('sendesta/', views.sendesta, name='sendesta'),
    path('vukode/', views.vukode, name='vukode'),
    path('bradstreet/', views.bradstreet, name='bradstreet'),
    path('ziteso/', views.ziteso, name='ziteso'),
    path('services/', views.services, name='services'),
    path('team/', views.team, name='team'),
    path('testimonial/', views.testimonial, name='testimonial'),
    path('__debug__/', include(debug_toolbar.urls)),
     path("config/", views.stripe_config),
    path("create-checkout-session-loan-origin-fee/<int:plan_id>/",
         views.Createloanoriginfeesession, name="create-checkout-session-loan-origin-fee"),
     path("create-checkout-session-subscription/<int:plan_id>/",
         views.Createloansubcriptionsession, name="create-checkout-session-loan-origin-fee"),
    path("success-loan-origin-fee/<int:plan_id>/", views.CreateloanoriginfeesessionSucess,
         name="success-loan-origin-fee"),
         
     path("success-loan-subscription/<int:plan_id>/", views.CreateloansubscriptionSucess,
         name="success-loan-subscription"),
    path("webhook", views.webhook, name="webhook"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mezzanine/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('dashboard/',include('dashboard.urls'))
]

dashboard/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.conf import settings
# Create your models here.


class ProductModel(models.Model):
    class Meta:
        abstract = True

    MONTH = 'Month'
    YEAR = 'Year'
    ONE_TIME = 'One time'
    recurring_choices = (
        (1, ONE_TIME),
        (2, MONTH),
        (3, YEAR)
    )

    # Override this in child classes
    type = 'product'

    name = models.CharField(max_length=500, default='Product', null=True)

    
    price = models.DecimalField(
        max_digits=100, default=0, decimal_places=2, validators=[MinValueValidator(0)])
    charge = models.DecimalField(
        max_digits=100, default=0, decimal_places=2, validators=[MinValueValidator(0)])
    recurring = models.IntegerField(
        choices=recurring_choices, default=1, null=True)

    # whitelabel_portal = models.ForeignKey(Subdomain, on_delete=models.CASCADE, null=True, blank=True)

    product_id = models.CharField(max_length=100, null=True, blank=True)
    price_id = models.CharField(max_length=100, null=True, blank=True)
    price_lookup = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name


class Product(ProductModel):
    description = models.TextField(null=True, blank=True)
    video = models.URLField(null=True, blank=True)
    link = models.URLField(blank=True, null=True)


class ProductPurchasedModel(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    payments_left = models.DecimalField(
        max_digits=100, default=0, decimal_places=2)
    amount_left = models.DecimalField(
        max_digits=100, default=0, decimal_places=2)
    username = models.CharField(blank=True, null=True, max_length=50)
    password = models.CharField(blank=True, null=True, max_length=50)
    link = models.URLField(blank=True, null=True)
    logged_link = models.URLField(blank=True, null=True)

    def __str__(self):
        return f"{self.product.name} {self.user}"


class ApplyLoanPlan(models.Model):
    name=models.CharField(blank=True, null=True, max_length=120)
    loan_type=models.CharField(blank=True, null=True, max_length=120)
    price = models.CharField(blank=True, null=True, max_length=120)
    subscription_stripe_id = models.CharField(max_length=150)
    origin_fee_stripe_id = models.CharField(max_length=150)
    origin_fee =models.CharField(blank=True, null=True, max_length=120)
    aproved_loan_amount =models.CharField(blank=True, null=True, max_length=120)
    duration = models.CharField(blank=True, null=True, max_length=120)
    def __str__(self):
        return "{} {}$ {}/months".format(self.name,self.price,self.duration)

dashboard/forms.py
from django.db import models
from django.forms import ModelForm
from users.models import CustomUser


class LoanApplicationForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = [
            'business_name',
            'business_address',
            'ein_number',
            'bank_name',
            'bank_account_number',

            'bank_routing_number',
        ]

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeForm, update_session_auth_hash
from django.contrib import messages
from django.http import HttpResponse
from django.views import View
from django.views.generic import TemplateView

from .models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from users.forms import CustomUpdateUserForm
from django.contrib.auth import get_user_model
from django.utils.safestring import mark_safe
from .forms import LoanApplicationForm
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.http.response import JsonResponse

User = get_user_model()


class ProfileView(View):
    def get(self, request):
        profile = request.user
        return render(request, 'dashboard/profile.html', {"profile": profile})


@login_required
def profile_update(request):
    if request.method == "POST":
        user_form = CustomUpdateUserForm(
            request.POST, request.FILES, instance=request.user)

        if user_form.is_valid():
            user_form.save()

            messages.success(request, 'Your profile is updated successfully')
            return redirect('dashboard:profile-portal-home')
    else:
        user_form = CustomUpdateUserForm(instance=request.user)

    return render(request, 'dashboard/profile.html', {'user_form': user_form})


@login_required
def plans(request):
    if request.method == "GET":
        return render(request, 'dashboard/plans.html')


@login_required
def dashboard(request):

    print('from index.html')
    user = request.user
    if not user.loan_subscription_added :
        messages.warning(
            request, mark_safe('<p>Please fill up your bank details to continue <a href="/dashboard/apply_for_loan/1" style="color:pink;">Get Started</a></p>'))
        bank_details = False

    else:
        bank_details = True
    print(user.bank_name, 'this is the user bank name')
    return render(request, 'dashboard/index.html')


@login_required
def Logout(request):
    logout(request)
    print('the user is logged out')
    return redirect('/')


def login(request):
    context = {}
    context['title'] = 'Login'
    if request.user.is_authenticated:
        messages.info(request, 'You have been already logged in')
        return redirect('dashboard:home')
    if request.method == 'GET':
        global nxt
        nxt = request.GET.get('next')
    if request.method == 'POST':
        print(request.POST)
        username = request.POST.get('email')
        password = request.POST.get('password')
        print(username, password)
        user = authenticate(request, username=username, password=password)
        print(user)
        if user is not None:
            auth_login(request, user)
            messages.success(request, 'You are logged in ')
            print('the use is logged in ')
            return redirect('dashboard:home')
        else:
            print('the user is not logged in')
            messages.error(request, 'Username or maybe Password is incorrect')
    return render(request, 'dashboard/auth-login.html')


def register(request):
    context = {}
    context['title'] = 'Create Account'
    if request.user.is_authenticated:
        messages.info(request, 'You have been already registered')
        return redirect('dashboard:home')
    if request.method == 'POST':
        print(request.POST)
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        business_address = request.POST.get(
            'business_address'
        )
        business_name = request.POST.get('business_name')
        print(password, 'password =============')
        user_created = User.objects.create_user(username=username, email=email, password=password,
                                                business_address=business_address, business_name=business_name
                                                )
        user = authenticate(
            username=username, password=password)

        print(user)
        # auth_login(request, user)
        messages.success(request, 'Account succesfully created')
        return redirect('dashboard:login')
    return render(request, 'dashboard/auth-register.html')


class FinancingPortalHomeView(View):

    def get(self, request):
        profile = request.user.profile
        return render(request, 'FinancingPortalHomePage.html', {"profile": profile})


class FinancingPortalProductsPurchasedView(View):

    def get(self, request):

        products = ProductPurchasedModel.objects.filter(user=request.user)
        return render(request, 'dashboard/FinancingPortalProductsPurchased.html', {"products": products})


class FinancingPortalConfirmPurchaseView(View):
    def get(self, request, pk):
        product = Product.objects.get(id=pk)
        credit_line = request.user.credit_line
        final_credit_line = credit_line-product.price

        return render(request, 'dashboard/FinancingPortalConfirmPurchase.html', {
            "product": product,
            "credit_line": credit_line,
            'final_credit_line': final_credit_line,

        })

    def post(self, request, pk, **kwargs):
        product = Product.objects.get(id=pk)
        current_user = User.objects.get(id=request.user.id)
        current_user.credit_line = current_user.credit_line-product.price
        purchase = ProductPurchasedModel(
            user=request.user,
            product=product,
            link=product.link,
        )

        current_user.save()
        purchase.save()
        return redirect('dashboard:products-purchased')


class FinancingPortalPurchaseProductsView(View):

    def get(self, request):
        user = request.user
        user_purchased = ProductPurchasedModel.objects.filter(
            user=request.user)
        print(user_purchased)
        if user_purchased:
            products = Product.objects.exclude(
                id=user_purchased.first().product.id)
        else:
            print('inside the else statement in products purchased view')
            products = Product.objects.all()

        if user.bank_name == "" or user.bank_routing_number == "" or user.bank_account_number == "" or user.voided_check_or_direct_deposit_form == "":
            messages.warning(
                request, 'You need to fill your bank info to purchase products')
            bank_details = False
            print('inside if statement')
        else:
            bank_details = True
        return render(request, 'dashboard/FinancialPortalPurchaseProducts.html', {
            "products": products,
            "bank_details": bank_details,

        })

    def post(self, request):

        prod_id = request.POST.get('product_id')
        user = request.user
        print(prod_id)
        return HttpResponse(prod_id)
        # ProductPurchasedModel.objects.create(user=user, product=prod_id)


class FinancingPortalPaymentsView(View):

    def get(self, request):
        prods = ProductPurchasedModel.objects.filter(user=request.user)
        amount_left = 0
        payments_left = 0
        for i in prods:
            amount_left += i.amount_left
            payments_left += i.payments_left

        return render(request, 'dashboard/FinancingPortalPayments.html', {
            "amount_left": amount_left,
            "payments_left": payments_left
        })


class FinancingPortalAccessSoftware(TemplateView):
    template_name = 'dashboard/FinancingPortalProductsAccessSoftware.html'

    def get_context_data(self, **kwargs):
        products = ProductPurchasedModel.objects.filter(user=self.request.user)
        return {"products": products}


@login_required
def apply_for_loan(request, step):
    print(step)
    context = {}
    context['basic'] = ApplyLoanPlan.objects.filter(loan_type="basic").first()
    context['standard'] = ApplyLoanPlan.objects.filter(
        loan_type="standard").first()
    context['premium'] = ApplyLoanPlan.objects.filter(
        loan_type="premium").first()
    if step == "1" or None:
        d_form = LoanApplicationForm(instance=request.user)
        context['form'] = d_form
        print("step 1")
        if request.method == "POST":
            d_form = LoanApplicationForm(request.POST, instance=request.user)
            print("p")
            print(d_form.errors)
            messages.warning(
                request, d_form.errors)
            if d_form.is_valid():
                print(d_form.cleaned_data)
                d_form.save()
                return redirect('dashboard:apply_for_loan', step=2)
    elif step == "subscriptionbasic":
        print('subscriptionbasic')
        context['allplans'] = ApplyLoanPlan.objects.filter(loan_type="basic")


    elif step == "subscriptionstandard":
        print('subscriptionstandard')
        context['allplans'] = ApplyLoanPlan.objects.filter(loan_type="standard")

    elif step == "subscriptionpremium":
        print('subscriptionpremium')
        context['allplans'] = ApplyLoanPlan.objects.filter(loan_type="premium")

    context['step'] = step

    return render(request, "dashboard/applyforloan.html", context)

dashboard/templates/dashboard/auth-register.html
{% extends "base.html" %}
{% load static %}

{% block content %} 
<style>
  @import url('https://fonts.googleapis.com/css?family=Raleway:400,700');

* {
	box-sizing: border-box;
	margin: 0;
	padding: 0;	
	font-family: Raleway, sans-serif;
}

body {
	background: linear-gradient(90deg, #eeeeee, #596AF3);		
}

.container {
	display: flex;
	align-items: center;
	justify-content: center;
	min-height: 100vh;
}

.screen {		
	background: linear-gradient(90deg, #ffffff, hsl(233, 50%, 68%));		
	position: relative;	
	height: 80%;
	width: 360px;	
	box-shadow: 0px 0px 24px #5C5696;
}

.screen__content {
	z-index: 1;
	position: relative;	
	height: 100%;
}

.screen__background {		
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	z-index: 0;
	-webkit-clip-path: inset(0 0 0 0);
	clip-path: inset(0 0 0 0);	
}

.screen__background__shape {
	transform: rotate(45deg);
	position: absolute;
}

.screen__background__shape1 {
	height: 520px;
	width: 520px;
	background: #FFF;	
	top: -50px;
	right: 120px;	
	border-radius: 0 72px 0 0;
}

.screen__background__shape2 {
	height: 220px;
	width: 220px;
	background: #6C63AC;	
	top: -172px;
	right: 0;	
	border-radius: 32px;
}

.screen__background__shape3 {
	height: 540px;
	width: 190px;
	background: linear-gradient(270deg, #5D54A4, #6A679E);
	top: -24px;
	right: 0;	
	border-radius: 32px;
}

.screen__background__shape4 {
	height: 400px;
	width: 200px;
	background: #7E7BB9;	
	top: 420px;
	right: 50px;	
	border-radius: 60px;
}

.login {
	width: 320px;
	padding: 30px;
}

.login__field {
	padding: 20px 0px;	
	position: relative;	
}

.login__icon {
	position: absolute;
	top: 30px;
	color: #7875B5;
}

.login__input {
	border: none;
	border-bottom: 2px solid #ffffff;
	background: none;
	padding: 10px;
	padding-left: 24px;
	font-weight: 700;
	width: 75%;
	transition: .2s;
}

.login__input:active,
.login__input:focus,
.login__input:hover {
	outline: none;
	border-bottom-color: #6A679E;
}

.login__submit {
	background: #fff;
	font-size: 14px;
	margin-top: 30px;
	padding: 16px 20px;
	border-radius: 26px;
	border: 1px solid #D4D3E8;
	text-transform: uppercase;
	font-weight: 700;
	display: flex;
	align-items: center;
	width: 100%;
	color: #4C489D;
	box-shadow: 0px 2px 2px #5C5696;
	cursor: pointer;
	transition: .2s;
}

.login__submit:active,
.login__submit:focus,
.login__submit:hover {
	border-color: #6A679E;
	outline: none;
}

.button__icon {
	font-size: 24px;
	margin-left: auto;
	color: #7875B5;
}

.social-login {	
	position: absolute;
	height: 140px;
	width: 160px;
	text-align: center;
	bottom: 0px;
	right: 0px;
	color: #fff;
}

.social-icons {
	display: flex;
	align-items: center;
	justify-content: center;
}

.social-login__icon {
	padding: 20px 10px;
	color: #fff;
	text-decoration: none;	
	text-shadow: 0px 0px 8px #7875B5;
}

.social-login__icon:hover {
	transform: scale(1.5);	
}
</style>
<div class="container">
	<div class="screen">
		<div class="screen__content">
			<form class="login" action="{% url 'dashboard:register' %}" method="POST" autocomplete="off">
        {% csrf_token %}
				<div class="login__field">
					<i class="login__icon fas fa-user"></i>
					<input type="text" class="login__input" id="email" required name="username" placeholder="Username">
				</div>
        <div class="login__field">
					<i class="login__icon fas fa-user"></i>
					<input type="text" class="login__input" id="username"  name="business_name" placeholder="Business Name">
				</div>
        <div class="login__field">
					<i class="login__icon fas fa-user"></i>
					<input type="text" class="login__input" id="email" name="business_address" placeholder="Business Address">
				</div>
        <div class="login__field">
					<i class="login__icon fas fa-user"></i>
					<input type="email" class="login__input" id="email" required name="email" placeholder="Email">
				</div>
				<div class="login__field">
					<i class="login__icon fas fa-lock"></i>
					<input type="password" class="login__input" placeholder="Password" id="password" required  name="password" >
				</div>
        
				<button class="button login__submit" type="submit">
					<span class="button__text">Register Now</span>
					<i class="button__icon fas fa-chevron-right"></i>
				</button>				
			</form>
			<div class="social-login">
				<div class="social-icons">

				</div>
			</div>
		</div>
		<!-- <div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>		
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>		 -->
	</div>
</div>

  <!-- <div style="height: 70vh; padding-top:150px">
<center>
<div style="width:400px; ">

<form action="{% url 'dashboard:register' %}" method="post" enctype="multipart/form-data">

  {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">User Name</label>
    <input  type="text" class="form-control form-control-lg" id="username" name="username" placeholder="Enter your username">
    
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Business Name</label>
    <input  type="text" class="form-control form-control-lg" id="username"  name="business_name" placeholder="Enter your Business Name">
    
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Business Address</label>
    <input  type="text" class="form-control form-control-lg" id="username" name="business_address" placeholder="Enter your Business Address">
    
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email</label>
   <input type="text" class="form-control form-control-lg" id="email" name="email" placeholder="Enter your email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input  type="password" class="form-control form-control-lg" id="password" name="password" placeholder="Enter your password">
  </div>
  <br/>
  <button type="submit" class="btn btn-primary">Register</button>
</form>
<div class="form-note-s2 pt-4"> Already have an account ? <a href="{% url 'dashboard:login' %}"><strong>Sign in instead</strong></a>
</div>

</div>
</center>
</div> -->

{% endblock content %}

dashboard/templates/dashboard/darksidetab.html
<div class="nk-apps-sidebar is-dark">
    <div class="nk-sidebar-element">
      <div class="nk-sidebar-body">
        <div class="nk-sidebar-content" data-simplebar>
          <div class="nk-sidebar-menu">
            <!-- Menu -->
            <ul class="nk-menu apps-menu">
              
              
            </ul>
          </div>
          <div class="nk-sidebar-footer">
            <ul class="nk-menu nk-menu-md">
              <li class="nk-menu-item">
                <a href="#" class="nk-menu-link" title="Settings">
                  <span class="nk-menu-icon"
                    ><em class="icon nii"></em
                  ></span>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="nk-sidebar-profile nk-sidebar-profile-fixed dropdown">
          <a href="#" data-toggle="dropdown" data-offset="50,-60">
            <div class="user-avatar">
              <span>AB</span>
            </div>
          </a>
          <div class="dropdown-menu dropdown-menu-md ml-4">
            <div class="dropdown-inner user-card-wrap d-none d-md-block">
              <div class="user-card">
                <div class="user-avatar">
                  <span>AB</span>
                </div>
                <div class="user-info">
                  <span class="lead-text">{{request.user.username}}</span>
                  <span class="sub-text text-soft">info@softnio.com</span>
                </div>
              </div>
            </div>
            <div class="dropdown-inner">
              <ul class="link-list">
                <li>
                  <a href="{% url "dashboard:profile-portal-home" %}"
                    ><em class="icon ni ni-user-alt"></em
                    ><span>View Profile</span></a
                  >
                </li>
                <li>
                  <a href="{% url "dashboard:update-profile" %}"
                    ><em class="icon ni ni-setting-alt"></em
                    ><span>Account Setting</span></a
                  >
                </li>
               
                <li>
                  <a class="dark-switch" href="#"
                    ><em class="icon ni ni-moon"></em
                    ><span>Dark Mode</span></a
                  >
                </li>
              </ul>
            </div>
            <div class="dropdown-inner">
              <ul class="link-list">
                <li>
                  <a href="{% url "dashboard:logout" %}"
                    ><em class="icon ni ni-signout"></em
                    ><span>Sign out</span></a
                  >
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

dashboard/templates/dashboard/navbar.html
<!-- main header @s -->
{% load static %}
<div class="page-main-header">
    <div class="main-header-right row m-0">
      <div class="main-header-left">
        <div class="logo-wrapper"><a href="/"><img class="img-fluid" width="62.074" height="65.771" src="{% static 'dashboard/assets/images/logo.png' %}" alt=""></a></div>
        <div class="dark-logo-wrapper"><a href="/"><img class="img-fluid"  width="62.074" height="65.771" src="{% static 'dashboard/assets/images/logo.png' %}" alt=""></a></div>
        <div class="toggle-sidebar"><i class="status_toggle middle" data-feather="align-center" id="sidebar-toggle"></i></div>
      </div>
      
      <div class="nav-right col pull-right right-menu p-0">
        <ul class="nav-menus">
          <li><a class="text-dark" href="#!" onclick="javascript:toggleFullScreen()"><i data-feather="maximize"></i></a></li>
         
            <div class="mode"><i class="fa fa-moon-o"></i></div>
          </li>
        <li> </li>
          <li class="onhover-dropdown p-0">
            <button class="btn btn-primary-light" type="button"><a href="{% url "dashboard:logout" %}"><i data-feather="log-out"></i>Log out</a></button>
          </li>
        </ul>
      </div>
      <div class="d-lg-none mobile-toggle pull-right w-auto"><i data-feather="more-horizontal"></i></div>
    </div>
  </div>

dashboard/templates/dashboard/profile.html
{% extends "dashboard/dashboard.html" %} {% load static %} {% block content %}
{% load crispy_forms_tags %}

<div class="nk-content">
  <div class="container-fluid">
    {% if user_form %}
    <div class="form-content">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ user_form | crispy }}
        <br /><br />
        <button type="submit" class="btn btn-dark btn-lg">Save Changes</button>
        
      </form>
    </div>
    {% else %}
    <section class="main-content">
        <div class="card card-bordered h-100">
            <div class="card-inner mb-n2">
              <div class="card-title-group">
                <div class="card-title card-title">
                  <h3 class="title">Profile</h3>
                </div>
               
              </div>
            </div>
            <div
              class="nk-tb-list is-loose traffic-channel-table"
            >
            <table class="table table-lg">
                <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Bank Name</th>
                    <th>Bank Account Number</th>
                    <th>Bank Routing</th>

                </tr>
                <tr>
                    <td>{{profile.username}}</th>
                    <td>{{profile.email}}</th>
                    <td>{{profile.bank_name}}</th>
                    <td>{{profile.bank_account_number}}</th>
                    <td>{{profile.bank_routing_number}}</th>
                </tr>
    
              </table>
              <!-- .nk-tb-item -->
            </div>
            <!-- .nk-tb-list -->
          </div>
          </div>
         
          
      </section>

    <br />
    <a href="{% url 'dashboard:update-profile' %}" class="btn btn-dark btn-sm"
      >UPDATE Profile</a
    >. {% endif %}
  </div>
</div>
{% endblock content %}

dashboard/templates/dashboard/sidetabs.html
{% load static  %}

<header class="main-nav">
  <div class="sidebar-user text-center">
  </div>
  <nav>
    <div class="main-navbar">
      <div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
      <div id="mainnav">           
        <ul class="nav-menu custom-scrollbar">
          <li class="nav-header">
            <div class="dropdown profile-element">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <span class="clear">
                  <span class="block m-t-xs"><strong class="font-bold">{{request.user.username}}</strong></span>
                  <span class="text-muted text-xs block">{{request.user.email}}<b class="caret"></b></span>
                </span>
              </a>
              <ul class="dropdown-menu animated fadeInRight m-t-xs">
                <li><a class="dropdown-item" href="{% url "dashboard:update-profile" %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url "dashboard:logout" %}">Logout</a></li>
              </ul>
            </div>
            <div class="logo-element">
              <img src="{% static 'dashboard/assets/images/logo-icon.png' %}" alt="">
            </div>
         
         
         
      
          <li class="sidebar-main-title">
            <div>
              <h6>Dashboard        </h6>
            </div>
          </li>
          <li><a class="nav-link menu-title link-nav" href="{% url 'dashboard:home' %}"><i data-feather="navigation-2"></i><span>Dashboard</span></a></li>
          <li><a class="nav-link menu-title link-nav" href="{% url 'dashboard:purchase-products' %}"><i data-feather="file"></i><span>Purchase Cloud Software Products</span></a></li>
          <li ><a class="nav-link menu-title link-nav" href="{% url 'dashboard:payments' %}"><i data-feather="aperture"></i><span>Payments</span></a></li>
          <li ><a class="nav-link menu-title link-nav" href="{% url 'dashboard:products-access' %}"><i data-feather="anchor"></i><span>Access Cloud Software Products</span></a></li>
          <li><a href="{% url "dashboard:profile-portal-home" %}" class="nav-link menu-title link-nav">
            <i class="flaticon-013-checkmark"></i>
            <span class="nav-text">Profile</span>
          </a>
          </li>
          <li><a href="{% url "dashboard:logout" %}"  class="nav-link menu-title link-nav">
            <i ><svg  xmlns="http://www.w3.org/2000/svg" class="text-danger" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
            </i>
            <span class="nav-text">Logout</span>
          </a>
          </li>   
          
        </ul>
      </div>
      <div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
    </div>
  </nav>
</header>